
clustering_framework: cc
project_name: deep_clustering
group: cifar100
run_name: CC
dataset: cifar100_test
dataset_path: "./data/CIFAR100"

backbone: resnet34
proj_dim: 128

optimizer: adam
lr: 0.0003
weight_decay: 0.

epochs: 1000
eval_interval: 10
crop_size: 224
batch_size: 256

clusters: 100
clusterings: 20
